/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vvpofdanezbzpuweefse"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2cG9mZGFuZXpienB1d2VlZnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzQ0NjcsImV4cCI6MjA2OTYxMDQ2N30.2HfbykZcadDHyFITK7pL2ahOpDEuenytudsPIl-Iv-8"